language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - development
install: /bin/true
script: "mvn clean install"
notifications:
  email:
    recipients:
      - dbp-spotlight-developers@lists.sourceforge.net
    on_success: change 
    on_failure: change
  irc: "irc.freenode.org#dbpedia-spotlight"
